### ISSUE TITLE
`qrc://` is better than `qrcx://`

### ISSUE THREAD

**Issue by shenlebantongying** [yozhic/GoldenDict-Full-Dark-Theme#2]
One of the original GD's developers investigated exactly why `qrcx` exist before https://github.com/goldendict/goldendict/commit/bb06509582c9a1ab342f5b79c85c3e28a26b19bc https://github.com/goldendict/goldendict/commit/c415cede8509b1bc431fbda81f681c95be0281e0 

In today's GoldenDict, `qrcx` is just `qrc` but with some extra unnecessary steps.

```css
qrcx://localhost/icons/expand_article.png
```
can be simplified into

```css
qrc:///icons/expand_article.png
```

https://github.com/yozhic/GoldenDict-Full-Dark-Theme/blob/54b1cf8b8c744f8aae7479995ce9538d5761ab91/GoldenDict/styles/Dark/article-style.css#L390-L405

**Comment by shenlebantongying** [comment]
This change is not really important, just perfectionism/nitpicking.

**Comment by yozhic** [comment]
Thanks, [done](https://github.com/yozhic/GoldenDict-Full-Dark-Theme/commit/5c9e1a4e7c3f82b95b1ae1a7c86425687d4ed642) 🤝

**Comment by shenlebantongying** [comment]
Thanks :+1:
